### ISSUE TITLE
`generateMap` doc clarification

### ISSUE THREAD

**Issue by benmccann** [h-a-n-a/magic-string-rs#17]
The readme says:

> generateMap: Note that there is a huge overhead for rust for implementing the same API in Node, for more detail please refer to [this](https://github.com/h-a-n-a/magic-string-rs/blob/main/node/index.d.ts)

If I follow the "this" link, I'm just taken to a type definition file. I'm not sure how it explains what overhead might exist. Is that the correct link or perhaps I'm missing something?

**Comment by h-a-n-a** [comment]
The link is intended to show the API difference between _magic-string_ and _magic-string-rs_. As it does not give the map directly, you have to call `to_map` to get the underlying source map. See here for the original magic-string definition: https://github.com/Rich-Harris/magic-string/blob/634d205fcfb457e414ab53265adc4df8cc38a121/index.d.ts#L43-L62
